select * from sathish_users;

SELECT * FROM SATHISH_ROLES;

SELECT * FROM SATHISH_USERS_ROLES;


--password= admin
INSERT INTO SATHISH_USERS (EMAIL, NAME, PASSWORD, USERNAME) VALUES ('admin@gmail.com', 'Admin User', '$2a$12$iYgh2GGX8I0HgFs6MNqlLO2Ik3abfpFjLH/PsR2nHIVY7mhFp1sNq', 'admin');

--password = routhu
INSERT INTO SATHISH_USERS (EMAIL, NAME, PASSWORD, USERNAME) VALUES ('sathish@gmail.com', 'Sathish Routhu', '$2a$12$OHvPLIO1iymL0iUFfzT41eV5QUldXylOv3FoYs8UthCE8KrruEa7u', 'sathish');

-- password = ram123
INSERT INTO SATHISH_USERS (EMAIL, NAME, PASSWORD, USERNAME) VALUES ('ram@gmail.com', 'Ram Kumar', '$2a$12$Z7WMXesndzU7Ir7Js9Owo.W2w6Jf84AKzCqpqN6b1Au.ujMhLTN76', 'ram');

-- password = fasi
INSERT INTO SATHISH_USERS (EMAIL, NAME, PASSWORD, USERNAME) VALUES ('ahmed@gmail.com', 'Fasi Ahmed', '$2a$12$EgtnQkegpkh1o5YErXV3QeoMAmYsEIsI82knwdFMIwKDDKMPsYeEK', 'fasi');



INSERT INTO SATHISH_ROLES (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO SATHISH_ROLES (NAME) VALUES ('ROLE_USER');
INSERT INTO SATHISH_ROLES (NAME) VALUES ('ROLE_MODERATOR');



INSERT INTO SATHISH_USERS_ROLES VALUES(1,1);

INSERT INTO SATHISH_USERS_ROLES VALUES(1,2);

INSERT INTO SATHISH_USERS_ROLES VALUES(1,3);

INSERT INTO SATHISH_USERS_ROLES VALUES(2,1);

INSERT INTO SATHISH_USERS_ROLES VALUES(2,2);

INSERT INTO SATHISH_USERS_ROLES VALUES(2,3);

INSERT INTO SATHISH_USERS_ROLES VALUES(3,3);

INSERT INTO SATHISH_USERS_ROLES VALUES(4,3);

commit;